services:
  celery_worker:
    healthcheck: # 개발 환경에서는 사실상 항상 통과로 설정
      test: ["CMD", "bash", "-lc", "echo ok"]
      interval: 30s
      timeout: 5s
      retries: 1
  celery_beat:
    healthcheck:
      test: ["CMD", "bash", "-lc", "echo ok"]
      interval: 30s
      timeout: 5s
      retries: 1
  flower:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: korea_celery_flower_dev
    command: python -m celery flower --broker=${REDIS_URL:-redis://redis:6379/0} --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_URL=${REDIS_URL:-redis://redis:6379/0}
    depends_on:
      - redis
    networks:
      - korea_api_network
